---
- name: Allowing firewall ports
  include_tasks:
    file: "{{ ansible_facts['os_family'] }}_ports.yaml"
    apply:
      tags:
        - 'Allow firewall Ports'
  when: firewall_ports == "null"

- name: Allowing firewall services
  include_tasks:
    file: "{{ ansible_facts['os_family'] }}_services.yaml"
    apply:
      tags:
        - 'Allow firewall Services'
