---
- name: Allowing firewall ports
  tinclude_tasks:
    file: "{{ ansible_facts['os_family'] }}_ports.yaml"
    apply:
      tags:
        - 'Allow firewall Ports'
  when: firewall_ports is defined

- name: Allowing firewall ports
  tinclude_tasks:
    file: "{{ ansible_facts['os_family'] }}_services.yaml"
    apply:
      tags:
        - 'Allow firewall Ports'
  when: firewall_services is defined
