---
- name: Allow firewall ports
  # debug: msg="{{ firewall_ports }}"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ firewall_ports }}"
  when: firewall_ports not "null"
