---
- name: Allow firewall ports
  debug: msg="This is the value {{ firewall_ports }}"
  # firewalld:
  #   port: "{{ item }}"
  #   permanent: yes
  #   immediate: yes
  #   state: enabled
  # loop: "{{ firewall_ports }}"
  # when: firewall_ports is not "null"
