---
- name: Allow firewall ports
  debug: msg="No"
  when: firewall_ports == "sinko"
  # firewalld:
  #   port: "{{ item }}"
  #   permanent: yes
  #   immediate: yes
  #   state: enabled
  # loop: "{{ firewall_ports }}"
  # when: firewall_ports is not "null"
