---
- name: Allow firewall ports
  debug: msg="Not is null"
  when: {{ firewall_ports }} != 'null'
  # firewalld:
  #   port: "{{ item }}"
  #   permanent: yes
  #   immediate: yes
  #   state: enabled
  # loop: "{{ firewall_ports }}"
  # when: firewall_ports is not "null"
