---
- name: Allow firewall services
  debug: msg="{{ firewall_services }}"
  # firewalld:
  #   service: "{{ item }}"
  #   permanent: yes
  #   immediate: yes
  #   state: enabled
  #  loop: "{{ firewall_services }}"
