---
- name: Allow firewall services
  # debug: "{{ firewall_services }}"
  firewalld:
    port: "{{ firewall_ports }}"
    permanent: yes
    immediate: yes
    state: enabled
  # loop: "{{ firewall_ports }}"
