---
- name: Include os-specific vars
  include_vars: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_vars.yaml"
  tags:
    - 'idm'
    - 'idm-vars'

- name: Setting common task
  include_role:
    name: common
    apply:
      tags: 'Common tasks'
  vars:
    hostname: "{{ hostname_idm }}"
    domain: "{{ domain_idm }}"
    hosts_file: "{{ hosts_file_idm }}"

- name: Setting time
  include_role:
    name: settime
    apply:
      tags: 'Set time'
  vars:
    package: "{{ package_chrony_idm }}"
    chrony_conf_file: "{{ chrony_conf_file_idm }}"
    timezone: "{{ timezone_idm }}"
    chrony_service_name: "{{ chrony_service_name_idm }}"
    chrony_server: "{{ chrony_server_idm }}"

- name: Installing idm
  include_tasks:
    file: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version']}}_install.yaml"
    apply:
      tags:
        - 'Install idm packages'

- name: Setup firewall
  include_role:
    name: firewall
    apply:
      tags: 'Setup Firewall'
  vars:
    firewall_services: "{{ item }}"
  loop: {{ firewall_services_idm }}""

- name: Setting os config
  include_tasks:
    file: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version']}}_config.yaml"
    apply:
      tags:
        - 'Set os config'
