---
- name: Include os-specific vars
  include_vars: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_vars.yaml"
  tags:
    - 'idm'
    - 'idm-vars'

- name: Setting common task
  inlclude_role:
    - name: ../common
