---
- name: Disable ipv6 on {{ nic }}
  sysctl:
    name: net.ipv6.conf.'{{ nic }}'.disable_ipv6
    value: '1'
    sysctl_file: "{{ sysctl_conf_file }}"
    sysctl_set: yes

- name: Disable ipv6 on default
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: "{{ sysctl_conf_file }}"
    sysctl_set: yes

- name: Edit sshd service
  lineinfile:
    path: "{{ ssh_config_file }}"
    regexp: '^#AddressFamily'
    line: AddressFamily inet
  notify: 'restart sshd'
