---
- name: Install idm streams
  dnf:
    name: "@idm:{{ module }}/{{ item }}"
    state: latest
  loop: "{{ streams }}"

- name: Install packages
  dnf:
    name: "{{ items }}"
    state: latest
  loop: "{{ packages }}"
