---
- name: Disable ipv6 on {{ item }}
  sysctl:
    name: net.ipv6.conf.{{ item }}.disable_ipv6
    value: '1'
    sysctl_file: "{{ sysctl_conf_file }}"
    sysctl_set: yes
  loop: "{{ nics }}"

- name: Edit sshd service
  lineinfile:
    path: "{{ ssh_config_file }}"
    regexp: '^#AddressFamily'
    line: AddressFamily inet
  notify: 'restart sshd'

# - name: Install Free-ipa
#   shell: "ipa-server-install --domain={{ domain_idm }} --realm={{ domain_idm | upper}} --ds-password={{ idm_password }} --admin-password={{ idm_password }} --hostname={{ hostname_idm }}.{{ domain_idm}} --ip-address={{ ansible_default_ipv4.address }} --reverse-zone={{ idm_reverse }}.in-addr.arpa. --forwarder={{ idm_forwarder }} --allow-zone-overlap --setup-dns --unattended "
#   register: idm_installation
#
# - debug: msg="{{ idm_installation }}"

- name: Edit DNS Server
  lineinfile:
    path: "{{ dns_file }}"
    regexp: '^nameserver'
    line: nameserver {{ ansible_default_ipv4.address }}
