---
- name: Setting Hostname
  include_tasks:
    file: hostname.yaml"
    apply:
      tags:
        - 'Set Hostname'

- name: Editing /etc/hosts file
  include_tasks:
    file: hosts.yaml"
    apply:
      tags:
        - 'Edit hosts file'

- name: Updating system
  include_tasks:
    file: update.yaml"
    apply:
      tags:
        - 'Update OS'
