---
- name: Update OS
  yum:
    name: '*'
    state: latest
  register: updates

- debug: msg="{{ updates }}"

# - name: Reboot system
#   reboot:
#   when: updates.changes.updated|flatten|select('regex', '^kernel$') is any
