---
- name: Update OS
  yum:
    name: '*'
    state: latest
  register: updates

- name: Check if reboot is necessary
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  register: reboot_hint

# - debug: msg="{{ reboot_hint.stdout }}"
- name: Reboot system
  reboot:
  when: reboot_hint.stdout == "reboot"
