---
- name: Set timezone
  command: timedatectl set-timezone "{{ timezone }}"

- name: Configure Chrony
  become: yes
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_conf_file }}"
  # notify: 'restart chrony'
