---
- name: Installing {{ package }}
  include_tasks:
    file: install.yaml
    apply:
      tags:
        - install

- name: Configuring {{ package }}
  include_tasks:
    file: config.yaml
    apply:
      tags:
        - 'config chrony'

- name: Enable service {{ chrony_service_name }}
  include_tasks:
    file: service.yaml
    apply:
      tags:
        - 'enable chrony'
