---
- name: Installing {{ package }}
  include_tasks:
    file: install.yaml
    apply:
      tags:
        - install

- name: Configure {{ package }}
  include_tasks:
    file: config.yaml
    apply:
      tags:
        - config
