---
- name: Import GPG Keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ gpgkeys }}"

- name: Install Repositories
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ repositories }}"
