---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Install foreman
  shell: foreman-installer --scenario katello --foreman-initial-admin-username admin --foreman-initial-admin-password 'temporal123' --tuning default

- name: Install plugins
  shell: foreman-installer --enable-"{{ item }}"
  loop: "{{ foreman_plugins }}"
