---
- name: Editing /etc/hosts
  include_tasks:
    file: hosts.yaml
    apply:
      tags:
        - 'edit hosts file'

# - debug: msg="{{ ansible_distribution_version.split(".") [0] }}"
#   register: distribution_version
#
# - name: Installing Repositories
#   include_tasks:
#     file: "{{ ansible_os_family | upper }}_R{{ distribution_version }}_repos.yaml"
#     apply:
#       tags:
#         - 'install repos'
#   when: "{{ distribution_version }} == 8 and {{ ansible_os_family | upper } == REDHAT"

- debug: msg= ansible_facts['os_family']
- debug: msg=ansible_facts['distribution_major_version']
