- name: Check /etc/hosts contains {{ ansible_default_ipv4.addres }}
  command: grep -Fxq "{{ ansible_default_ipv4.addres }}" /etc/hosts
  register: checkhostsfile

- debug: mgs="No ta"
  when: checkhostsfile.rc == 0
