---
- name: Editing /etc/hosts
  include_tasks:
    file: hosts.yaml
    apply:
      tags:
        - 'edit hosts file'

- name: Installing Repositories
  include_tasks:
    # file: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_repos.yaml"
    file: RedHat_R8_repos.yaml
    apply:
      tags:
        - 'install repos'
  when: ansible_facts['os_family'] == 'RedHat'
