---
- name: Editing /etc/hosts
  include_tasks:
    file: hosts.yaml
    apply:
      tags:
        - 'edit hosts file'
- debug: msg="{{ ansible_os_family | upper }}"
- debug: msg="{{ ansible_distribution_version }}"
