---
- name: Include os-specific vars
  include_vars: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_vars.yaml"
  tags:
    - 'foreman'
    - 'foreman-vars'

- name: Editing /etc/hosts
  include_tasks:
    file: hosts.yaml
    apply:
      tags:
        - 'edit hosts file'

- name: Task only for OS family RedHat
  block:
    - name: Opening Firewall ports
      include_tasks:
        file: "{{ ansible_facts['os_family'] }}_firewall.yaml"
        apply:
          tags:
            - 'firewall'

    - name: Installing Repositories
      include_tasks:
        file: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_repos.yaml"
        apply:
          tags:
            - 'install repos'
            
    - name: Installing Foreman
      include_tasks:
        file: "{{ ansible_facts['os_family'] }}_R{{ ansible_facts['distribution_major_version'] }}_install.yaml"
        apply:
          tags:
            - 'install foreman'
  when: ansible_facts['os_family'] == 'RedHat'
#   when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
