---
- name: Include os-specific vars
  include_vars: "{{ ansible_facts['distribution'] }}_R{{ ansible_facts['distribution_major_version'] }}_vars.yaml"
  tags:
    - 'foreman'
    - 'foreman-vars'

- name: Update OS
  yum:
    name: '*'
    state: latest
    
- name: Editing /etc/hosts
  include_tasks:
    file: hosts.yaml
    apply:
      tags:
        - 'edit hosts file'

- name: Opening Firewall ports
  include_tasks:
    file: firewall.yaml
    apply:
      tags:
        - 'firewall'

- name: Tasks only for CentOS
  block:
    - name: Installing Repositories
      include_tasks:
        file: "{{ ansible_facts['distribution'] }}_R{{ ansible_facts['distribution_major_version'] }}_repos.yaml"
        apply:
          tags:
            - 'install repos'
  when: ansible_facts['distribution'] == 'CentOS'

- name: Installing Foreman
  include_tasks:
    file: install.yaml
    apply:
      tags:
        - 'install foreman'
