---
- name: Import GPG Keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ gpgkeys }}"

- name: Install Repositories
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ repositories }}"

- name: Install Repositories OL
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ ol_repositories }}"
  when: ansible_facts['distribution'] == 'OracleLinux'
