---
- name: Install {{ foreman_package }}
  yum:
    name: "{{ foreman_package }}"
    state: latest
- name: Install foreman
  command: foreman-installer
  register: foreman

- debug: msg="{{ foreman }}"
