---
- name: Import Puppet repo key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ puppet_gpgkey }}"

- name: Install Puppet repo
  yum:
    name: "{{ puppet_repo }}"
    state: present

- name: Import Foreman repo key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ foreman_gpgkey }}"  

- name: Install Foreman repo
  yum:
    name: "{{ foreman_repo }}"
    state: present
