---
- name: Import GPG Keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ gpgkeys }}"

- name: Install Repositories
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ repositories }}"

- name: Enable epel Repository
  yum_repository:
    name: ol8_developer_EPEL
    description: Oracle Linux $releasever EPEL ($basearch)
    baseurl: https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/$basearch/
    gpgcheck: yes
    enabled: yes
  when: ansible_facts['distribution'] == 'OracleLinux'
