---
- name: Allow Foreman ports tcp
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 53/tcp
    - 80/tcp
    - 443/tcp
    - 3000/tcp
    - 8140/tcp
    - 3306/tcp
    - 5432/tcp
    - 8443/tcp
    - 5910/tcp
    - 5930/tcp
    - 67-69/udp
