---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Install foreman
  shell: foreman-installer --scenario katello --foreman-initial-admin-username --foreman-initial-admin-password 'temporal123'
  register: foreman

- debug: msg="{{ foreman }}"
